version: "3"
services:
  decoder:
    # replace username/repo:tag with your name and image details
    image: xdecoder
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "10086:10000"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    volumes:
      - db:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: asr
      MYSQL_ROOT_PASSWORD: admin

  visualizer:
      image: dockersamples/visualizer:stable
      ports:
        - "8080:8080"
      stop_grace_period: 1m30s
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      deploy:
        placement:
          constraints: [node.role == manager]

volumes:
  db:
